Repository operate-first/operate-first.github.io, pull requests merged in 2022-08, with the labels that each got.

#156 and to & - fitting into the box
  src/components/homepage/About.js
Labels: size/XS

#158 add the plugin
  .github/renovate.json
Labels: size/XS

#173 sample app updates
  content/posts/rh-distributed-tracing/index.mdx
Labels: size/M, approved, lgtm

#152 Added breakpoints to blog-card grid
  src/components/blog.tsx
Labels: approved, lgtm, size/S

#153 Added horizontal margin to blog-post wrapper
  src/components/post.tsx
Labels: approved, size/XS, lgtm

#174 add jaeger route and logs png
  content/posts/rh-distributed-tracing/index.mdx
  content/posts/rh-distributed-tracing/logs-with-traces.png
Labels: approved, lgtm, size/S

#181 update coloring book blog
  content/posts/sre-coloring-book/index.mdx
Labels: approved, lgtm, size/S

#182 Definition of operate first
  .gitignore
  content/posts/operate-first-defined-4-words/index.mdx
Labels: size/M, approved, lgtm, ok-to-test

#189 adding MOC Alliance & OpenInfra Labs Logo & Link v4
  src/assets/MOCAlliance-logo-white_transp.png
  src/assets/OpenInfraLabs-logo-white_transp.svg
  src/assets/RedHat-logo-white_transp.svg
  src/components/homepage/Footer.js
Labels: size/S, kind/website
