Repository operate-first/operate-first.github.io, pull requests merged in 2022-10, with the labels that each got.

#198 bi-weekly meetup landing page created
  src/components/meetup.js
  src/pages/meetup_lp.js
Labels: size/L, kind/website, triage/accepted, kind/experience, priority/critical-urgent, user/experience

#195 website: some cleanups, general fixes and issue related
  src/components/ServiceList.js
  src/pages/community-cloud.js
  src/pages/developer.js
  src/pages/getting-started.js
  src/pages/our-community.js
  src/pages/srepractices.js
Labels: size/L, approved, lgtm

#203 meetup page, update new meeting, get rid of _ml
  src/components/meetup.js
  src/pages/meetup.js
  src/pages/meetup_lp.js
Labels: size/M, approved, kind/website, triage/accepted, kind/experience, priority/critical-urgent

#204 meetup page, update new meeting, get rid of _ml
  src/components/homepage/Faq.js
  src/components/homepage/Footer.js
  src/components/homepage/HomePage.js
  src/components/homepage/Interest.js
  src/components/homepage/Navbar.js
  src/components/meetup.js
  src/pages/meetup_lp.js
Labels: size/M, approved, kind/website, triage/accepted, kind/experience, priority/critical-urgent

#206 Fix navbar jumping when in blog page
  src/components/blog.tsx
Labels: approved, size/XS, lgtm, hacktoberfest, hacktoberfest-accepted, needs-ok-to-test

#210 update meetup page, new date for next meeting
  src/components/meetup.js
Labels: approved, lgtm, size/S, priority/important-soon, kind/cleanup, kind/website, triage/accepted

#212 Update about OKD WG build work
  content/posts/journey-to-open-cloud--okd-update/index.md
Labels: size/M, approved

#213 updated to note new OKD MVP release
  content/posts/journey-to-open-cloud--okd-update/index.md
Labels: size/XS
