Repository operate-first/operate-first.github.io, pull requests merged in 2022-06, with the labels that each got.

#57 Operate First services list
  src/assets/services/argo.svg
  src/assets/services/dex.svg
  src/assets/services/grafana.svg
  src/assets/services/jupyterhub.svg
  src/assets/services/observatorium.svg
  src/assets/services/odh.png
  src/assets/services/redhat.svg
  src/components/ServiceList.js
  src/components/nav-tabs/Services.js
  src/pages/community-cloud.js
Labels: size/L, approved, lgtm

#64 Added new OPF logo & useful resources
  README.md
Labels: approved, lgtm, size/S

#59 Filling out & clarifying 'getting started' content
  src/pages/getting-started.js
Labels: size/M, approved, lgtm

#69 Small adjustments to mobile sizing and button color change
  src/components/homepage/About.js
  src/components/homepage/HomePage.js
Labels: size/M, approved, lgtm

#71 Fewer words and more clarity in menu
  src/components/homepage/Navbar.js
Labels: approved, size/XS, lgtm, kind/website

#73 Made things* click more noticable
  src/components/homepage/HomePage.js
Labels: approved, lgtm, size/S

#72 Evolving menu to add `/blog` link
  src/components/homepage/Navbar.js
Labels: approved, size/XS, lgtm, kind/website

#78 Fixed service catalog mobile responsiveness
  src/components/nav-tabs/Services.js
  src/pages/community-cloud-workloads.js
  src/pages/community-cloud.js
Labels: size/M, approved, lgtm

#79 Removed nav menu items bug on docs & train
  src/components/homepage/Footer.js
  src/components/homepage/Navbar.js
  src/pages/docs-training.js
  src/pages/getting-started.js
Labels: size/M, approved, lgtm

#75 Linking to Getting Started from all over
  src/components/nav-tabs/AboutPage.js
  src/components/nav-tabs/CommunityPage.js
  src/components/nav-tabs/DocTraining.js
  src/pages/community-cloud.js
Labels: size/S
