Repository operate-first/operate-first.github.io, pull requests merged in 2022-09, with the labels that each got.

#192 Update index.mdx
  content/posts/operate-first-defined-4-words/index.mdx
Labels: size/XS

#180 Community Cards
  src/components/elements/CommunityCard.js
  src/components/modules/ListOfCommunities.js
  src/pages/our-community.js
Labels: size/L, approved, lgtm

#194 google ga4 - add gatsby-plugin-google-gtag
  gatsby-config.js
  package-lock.json
  package.json
Labels: size/M, approved, lgtm, priority/important-soon, kind/cleanup, kind/website
