Repository operate-first/operate-first.github.io, pull requests merged in 2022-07, with the labels that each got.

#106 move renovate and update conf
  .github/renovate.json
  renovate.json
Labels: size/M

#90 add mantine themeing
  src/components/Layout.js
  src/components/Layout.tsx
  src/pages/about.js
Labels: size/M, approved

#92 feat: Update logos
  src/assets/landing-logo.svg
  src/assets/logo.png
  src/assets/top-logo.svg
Labels: size/L, approved, lgtm

#112 convert layout.tsx to .js
  src/components/Layout.js
  src/components/Layout.tsx
Labels: size/M

#81 README.md replace broken button image
  README.md
  docs/run-workflow-button.png
Labels: approved, size/XS, lgtm

#116 Update FAQ section, replacing the X
  src/components/homepage/About.js
  src/components/homepage/Faq.js
Labels: kind/documentation, approved, size/S, kind/website, sig/community

#121 layout all pages
  src/components/Layout.js
  src/components/Layout.tsx
  src/components/ServicesBoard.js
  src/components/homepage/HomePage.js
  src/components/nav-tabs/AboutPage.js
  src/components/nav-tabs/CommunityPage.js
  src/components/nav-tabs/DocTraining.js
  src/pages/about.js
  src/pages/action.js
  src/pages/community-cloud-workloads.js
  src/pages/community-cloud.js
  src/pages/data-scientist.js
  src/pages/developer.js
  src/pages/docs-training.js
  src/pages/getting-started.js
  src/pages/index.js
  src/pages/our-community.js
  src/pages/srepractices.js
Labels: approved, lgtm, size/XL

#128 color theme for main page
  src/components/Layout.css
  src/components/Layout.tsx
  src/components/ServicesBoard.js
  src/components/homepage/About.js
  src/components/homepage/Faq.js
  src/components/homepage/HomePage.js
  src/components/homepage/Interest.js
  src/pages/about.js
  src/pages/action.js
  src/pages/community-cloud.js
  src/pages/data-scientist.js
  src/pages/developer.js
  src/pages/docs-training.js
  src/pages/getting-started.js
  src/pages/index.js
  src/pages/our-community.js
  src/pages/srepractices.js
Labels: size/M, approved, lgtm

#89 new blog based on lekoart-core
  content/pages/.gitkeep
  content/posts/chaos-testing-guide/index.mdx
  content/posts/chaos-testing-guide/krkn-workflow.png
  content/posts/kubecon-valencia-eu-2022-trip-report/coufal-twitter.png
  content/posts/kubecon-valencia-eu-2022-trip-report/index.md
  content/posts/rh-distributed-tracing/index.mdx
  content/posts/rh-distributed-tracing/jaeger-overview.png
  content/posts/rh-distributed-tracing/jaeger-route.png
  content/posts/rh-distributed-tracing/jaeger-shot.png
  content/posts/rh-distributed-tracing/jaeger-trace.png
  content/posts/sre-coloring-book/index.mdx
  gatsby-browser.js
  gatsby-config.js
  package-lock.json
  package.json
  src/@lekoarts/gatsby-theme-minimal-blog-core/components/homepage.tsx
  src/@lekoarts/gatsby-theme-minimal-blog-core/components/post.tsx
  src/components/blog.tsx
  src/components/post.tsx
Labels: size/XXL, approved, lgtm, priority/important-soon, kind/website

#130 prettier
  .eslintrc.yml
  .pre-commit-config.yaml
  gatsby-config.js
  package-lock.json
  package.json
  src/@lekoarts/gatsby-theme-minimal-blog-core/components/homepage.tsx
  src/@lekoarts/gatsby-theme-minimal-blog-core/components/post.tsx
  src/components/Layout.tsx
  src/components/ServiceList.js
  src/components/ServicesBoard.js
  src/components/blog.tsx
  src/components/homepage/About.js
  src/components/homepage/Faq.js
  src/components/homepage/Footer.js
  src/components/homepage/HomePage.js
  src/components/homepage/Interest.js
  src/components/homepage/Navbar.js
  src/components/post.tsx
  src/pages/404.js
  src/pages/about.js
  src/pages/action.js
  src/pages/community-cloud.js
  src/pages/data-scientist.js
  src/pages/developer.js
  src/pages/docs-training.js
  src/pages/getting-started.js
  src/pages/index.js
  src/pages/our-community.js
  src/pages/srepractices.js
Labels: size/XXL

#141 new resolve to fix errors
  package-lock.json
Labels: size/XXL

#135 distributed-tracing updates (#23)
  content/posts/rh-distributed-tracing/index.mdx
Labels: size/M

#142 show all blog posts on overview not just 3
  src/@lekoarts/gatsby-theme-minimal-blog-core/templates/homepage-query.tsx
Labels: size/S

#143 renovate2
  .github/renovate.json
Labels: size/XS
