Repository operate-first/operate-first.github.io, pull requests merged in 2022-05, with the labels that each got.

#8 Added footer, improved Navbar, and more
  src/components/homepage/Faq.js
  src/components/homepage/Footer.js
  src/components/homepage/HomePage.js
  src/components/homepage/Interest.js
  src/components/homepage/Navbar.js
  src/pages/index.js
  static/RHLogo.png
Labels: size/L, approved, lgtm

#9 About page
  src/components/homepage/Navbar.js
  src/pages/about.js
Labels: size/M, approved, lgtm

#10 node16, bump packages
  .github/workflows/build_job.yaml
  package-lock.json
  package.json
Labels: size/XXL, approved, lgtm

#12 Navigation pages created
  src/components/homepage/Navbar.js
  src/components/nav-tabs/AboutPage.js
  src/components/nav-tabs/CommunityCloud.js
  src/components/nav-tabs/CommunityPage.js
  src/components/nav-tabs/DocTraining.js
  src/pages/about.js
  src/pages/community-cloud.js
  src/pages/community.js
  src/pages/docs-training.js
  src/pages/index.js
Labels: size/L, approved, lgtm

#11 update links for buttons
  src/components/homepage/Interest.js
  src/components/nav-tabs/CommunityCloud.js
  src/components/nav-tabs/CommunityPage.js
Labels: size/M, approved, lgtm

#17 Updated homepage information and buttons based on website WG discussions
  src/components/homepage/About.js
  src/components/homepage/Interest.js
Labels: size/M, approved, lgtm

#16 Add opf in action page
  src/components/homepage/ActionPage.js
  src/pages/action.js
Labels: size/M, approved, lgtm

#18 Fixed spacing between buttons and responsiveness
  src/components/homepage/Interest.js
Labels: size/L, approved, lgtm

#19 Prop-type errors and jsx errors fixed
  src/components/homepage/About.js
  src/components/homepage/Footer.js
  src/components/homepage/Navbar.js
  src/pages/404.js
  src/pages/about.js
  src/pages/action.js
  src/pages/community-cloud.js
  src/pages/community.js
  src/pages/docs-training.js
  src/pages/index.js
  src/pages/style.css
Labels: size/M, approved, lgtm

#22 fix branch in gh workflow
  .github/workflows/build_job.yaml
Labels: approved, size/XS, lgtm

#26 Fixed repeated text on homepage; added to the Our Purpose and Docs and Training pages
  src/components/homepage/About.js
  src/components/nav-tabs/AboutPage.js
  src/components/nav-tabs/DocTraining.js
Labels: size/M, approved, lgtm

#27 Add links for community cloud page
  src/pages/community-cloud.js
Labels: approved, lgtm, size/S

#24 Fixed styling, responsiveness, format of content
  src/components/homepage/HomePage.js
  src/components/homepage/Interest.js
  src/components/nav-tabs/AboutPage.js
  src/components/nav-tabs/CommunityPage.js
  src/components/nav-tabs/DocTraining.js
  src/pages/community-cloud.js
  src/pages/community.js
  src/pages/data-scientist.js
  src/pages/developer.js
  src/pages/srepractices.js
Labels: size/L, approved, lgtm

#28 npm audit fix
  package-lock.json
Labels: size/XXL, approved, lgtm

#30 action redirect
  gatsby-config.js
  package-lock.json
  package.json
  src/components/homepage/ActionPage.js
  src/pages/action.js
Labels: size/L, approved, lgtm

#31 community cloud page update
  src/pages/community-cloud.js
Labels: size/M, approved, lgtm

#32 Fixed some typos and spacing on the Our Purpose page (AboutPage.js)
  src/components/nav-tabs/AboutPage.js
Labels: size/M, approved, lgtm

#34 Added the getting started page with some initial content
  src/pages/getting-started.js
Labels: size/L, approved, lgtm

#35 stefwrite/main
  src/pages/getting-started.js
Labels: size/M

#36 add CNAME
  static/CNAME
Labels: size/XS

#37 remove path prefix
  gatsby-config.js
Labels: size/XS

#39 Added FAQ items and fixed padding issues
  src/components/homepage/Faq.js
  src/components/homepage/HomePage.js
  src/components/nav-tabs/AboutPage.js
  src/pages/community.js
  src/pages/data-scientist.js
  src/pages/developer.js
  src/pages/srepractices.js
Labels: size/M, approved, lgtm

#40 New MantineUI based 404 page
  src/pages/404.js
Labels: size/L, approved, lgtm

#42 Edit and (IMHO) improvements to blurbs
  src/components/homepage/About.js
Labels: approved, lgtm, size/S

#46 add google analytics
  gatsby-config.js
  package-lock.json
  package.json
Labels: size/M, approved, lgtm

#45 rename community landing page
  src/components/homepage/Navbar.js
  src/components/nav-tabs/AboutPage.js
  src/pages/docs-training.js
  src/pages/getting-started.js
  src/pages/our-community.js
Labels: approved, size/XS, lgtm

#44 Relating the question back to the main statement
  src/components/homepage/About.js
Labels: approved, size/XS, lgtm

#55 New logo and background mock up
  src/assets/concrete.png
  src/assets/opf-logo.png
  src/components/homepage/About.js
  src/components/homepage/Faq.js
  src/components/homepage/HomePage.js
  src/components/homepage/Interest.js
  src/components/homepage/Navbar.js
Labels: size/M, approved, lgtm, ok-to-test

#43 Conceptual content edits across new nav pages
  src/assets/docs-training-layered-learning.png
  src/components/nav-tabs/AboutPage.js
  src/components/nav-tabs/CommunityPage.js
  src/components/nav-tabs/DocTraining.js
  src/pages/developer.js
  src/pages/getting-started.js
  src/pages/srepractices.js
Labels: size/L, approved, lgtm

#56 Added Favicon to website
  gatsby-config.js
  package-lock.json
  package.json
Labels: size/M, approved, lgtm
